apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      priorityClassName: research-low
      containers:
        - name: hyperparameter_optim_test
          image: ls6-stud-registry.informatik.uni-wuerzburg.de/studrudolph/pytorch-test:0.0.1
          imagePullPolicy: "IfNotPresent"
          env:
            - name: TEST
              value: "hello"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "2Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "2Gi"
          command: ["python3", "-c", "print('HelloWorld')"]
          volumeMounts:
            - mountPath: /home/stud/test_cluster_durchlauf # directory IN the container
              name: localdir # matches volume-name from below
      imagePullSecrets:
        - name: lsx-registry
      restartPolicy: "Never"
      volumes:
        - name: localdir
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20  # Not important for you, just copy along
            user: studrudolph  # <namespace>
            path: "/home/stud/test_cluster_durchlauf" # The path you want to mount
            secretRef: # The name of the secret for auth. Is always "ceph-secret"
              name: ceph-secret